### ISSUE TITLE
Unable to build Hello Window due to package manager weirdness

### ISSUE THREAD

**Issue by Niphre** [SwiftGL/examples#3]
I cannot get the package manager to work, even when I used the version of the package.swift posted in the swiftGL/examples it throws a whole bunch of errors about arguments being in the wrong order. Even when I put them in the right order the compiler throws this error:

`error: manifest parse error(s):
/Users/Isaac/Desktop/OpenGL/Hello Window/Package.swift:10:10: error: type 'Target' has no member 'target'
        .target(name: "example", dependencies: ["SGLMath", "SGLImage", "SGLOpenGL"], path: "."),
        ~^
`

I am using this swift version: 
Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)
Target: x86_64-apple-macosx10.9

I have never used the swift package manager so any help would be appreciated.

**Comment by jkolb** [comment]
Those seem like the kind of errors that would show up if a different version of the swift tools were being used, or if a different version of the Package API in Package.swift was getting used. You have to be careful looking up stuff on the package manager on the Internet as it can be tough to tell if the information you are getting is for Swift 3 or Swift 4. Documentation is a bit sparse unfortunately.

Here is some more info on the package manager: https://github.com/apple/swift-package-manager/blob/master/Documentation

And here is the documentation for Swift 4 version: https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescriptionV4.md

Here are the versions I'm using:

swift package --version
Apple Swift Package Manager - Swift 4.0.0-dev (swiftpm-13752)

swift --version
Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)
Target: x86_64-apple-macosx10.9

**Comment by Niphre** [comment]
Strange, I checked my version of the swift package manager and it is the exact same version that you are using. Could you look at my package.swift and tell me what I am doing wrong? Because I am at a loss for what I am doing wrong.

**Comment by jkolb** [comment]
I could try, but would need a link to the file.

**Comment by Niphre** [comment]
Ok, here is my package .swift file, the txt extension is just so I can attach it to the post.
[Package.swift.txt](https://github.com/SwiftGL/examples/files/1682790/Package.swift.txt)

**Comment by jkolb** [comment]
According to this: https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescriptionV4.md <https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescriptionV4.md>

The order of parameters is: name, pkgConfig, providers, products, dependencies, targets, swiftLanguageVersions. It looks like you are using the version for Swift 3 which matches what you have.

**Comment by Niphre** [comment]
Sorry for not responding sooner, it does seem that for some reason it is using the swift 3 version of the package manager even though the swift package --version command outputs: Apple Swift Package Manager - Swift 4.0.0-dev (swiftpm-13752).

After changing my Package.swift to comply with version 3 of the package manager I was able to get it to build!  I am now working through the tutorials, thank you so much for creating this resource and bearing with my silly mistakes.
